### ISSUE TITLE
Manage the app from a tablet

### ISSUE THREAD

**Issue by AlejandroAbBlanc** [AlejandroAbBlanc/GESPRO-TAREA2-DIA3#17]

**Comment by gdf1001-ubu** [comment]
De los siguientes botones: Detener, Informe, Desinstalar, Reembolso, Mover a la tarjeta SD, Mover a dispositivos de almacenamiento, Borrar datos, Limpiar chache, Predeterminados

¿Cuáles hay que implementar en la pantalla de detalles de la aplicación?

**Comment by AlejandroAbBlanc** [comment]
Tendrían que aparecer los botones: Detener, Informe, Desinstalar, Reembolso, Mover a la tarjeta SD, Mover a dispositivos de almacenamiento y Borrar datos
