### ISSUE TITLE
Get account details

### ISSUE THREAD

**Issue by gdf1001-ubu** [AlejandroAbBlanc/GESPRO-TAREA2-DIA3#4]

**Comment by AlejandroAbBlanc** [comment]
¿Cuáles son los datos concretos que debería devolver esta función sobre la cuenta del usuario?

**Comment by gdf1001-ubu** [comment]
Nombre, Apellidos, DNI y rol en la aplicación

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
michaelliao, @dav1dk1m, @lucasea777, @amrtawfik160, @sfrassanito, @spnraju, @AlanNggg, @copmoa, @gileann, @rcolomina, @urmil22, @camilanovaes, @vasafred, @kaal8733, @AntonioA-FS, @MickHerbivore, @mvshalamov, @ASeriousMister, @mrbathinape, @practicalyst, @aka863, @huyuhui123, @Tangoy, @mrasyadc, @Cajun2017, @arun-aswathanarayan, @appsplash99, @Abdulkbk, @giovannidisiena, @lucienrey, @Alexemidio, @WhySoSilent, @BertrandConxy, @raymondclowe, @dx670, @azmanabdlh, @Annel702, @yuloskov, @jiajunhuang, @mayank0508, @stroncis, @dB2510, @infredulous, @legendary-jld, @exherb, @vampireneo, @huangkaiqiao, @sanjaynath, @ngraton, @nat236919
